### ISSUE TITLE
Add `kctrl` to the list of apps installed as part of the action

### ISSUE THREAD

**Issue by praveenrewar** [carvel-dev/setup-action#202]
Add [kctrl](https://carvel.dev/kapp-controller/docs/v0.38.0/install/#installing-kapp-controller-cli-kctrl) (kapp-controller's native cli) to the list of apps installed as part of the action.
kctrl has been part of kapp-controller releases since [v0.34.0](https://github.com/vmware-tanzu/carvel-kapp-controller/releases/tag/v0.34.0)

**Comment by jbrunton** [comment]
Hi @praveenrewar! Thanks for the issue. I created a draft PR here: #203.

I notice that the format of the checksums in the release notes for `kctrl` is a little different from the other Carvel repos. They all provide the output of `md5sum` (which always has two spaces between the hash and the filename) and prefix the binary name with the relative path signifier `./`. For example:

```
5fd3afbe09a66fc9e91252c57448045eeeab1ee3f6d305da6f9885186b744e67  ./kbld-darwin-amd64
2962cd78c6c45cf3f03ca76c52ca7517ed5f2ceba6ed1b3d594a16d516ef05a2  ./kbld-darwin-arm64
67c86ece94a3747b2e011a5b72044b69f2594ca807621b1e1e4c805f6abcaeef  ./kbld-linux-amd64
658725c5dab5349dd4cb826ff9278749f093ed2275aadf51dc994265e6599b2c  ./kbld-linux-arm64
9dcb4d6db2901257f8f23059c13b41d37ef8b8b36f27d909cceb81934fc9e862  ./kbld-windows-amd64.exe
04c51f4aa92d117d22513727ee37cda1b5ae18bf94a223093f11727d0ba878b4  ./kbld-windows-arm64.exe
```

However, per the failing tests in the PR, the release notes for `kctrl` are sometimes in a different format (with variations in the number of spaces between the hash and the binary, and not all binaries prefixed with the relative path signifier). This results in failures like this:

    Unable to verify checksum for kctrl-linux-amd64. Expected to find "4442f03491aca0299adad3b44061930dccf57eea47cc8289319cb1fc4d9b4029  ./kctrl-linux-amd64" in release notes. 

Would you be up for amending the release notes for `kctrl` to match the format of other Carvel repos? There's something to be said for consistency, and I would prefer to avoid adding regexes or conditionals to the security check if possible, as that introduces a new bug surface area.

**Comment by praveenrewar** [comment]
Thank you so much for the quick turn around @jbrunton. Sure, I will add the `./` with the filenames in the release notes.

**Comment by praveenrewar** [comment]
Hi @jbrunton! We are planning to make a kapp-controller release next week (which will have the release notes in the correct format), is it okay to merge the PR after that? 
We are okay with supporting kctrl from the next release in the Github action (just trying to avoid updating the release notes as much as possible)

**Comment by jbrunton** [comment]
@praveenrewar: sure thing! Let me know once that's released and then I can re-run the tests in the PR to check everything works as expected.

**Comment by praveenrewar** [comment]
Awesome! Sure, I will let you know :)

**Comment by praveenrewar** [comment]
Hi @jbrunton! kapp-controller v0.38.4 is released and the tests on the PR seem to be passing now (after I re-triggered them) 🚀 
The release workflow is also updated to have the checksums in a consistent format.

**Comment by jbrunton** [comment]
@praveenrewar: Thanks for making those changes! I've merged the PR and released a new version of the action, so I'll close this issue now.
