### ISSUE TITLE
Cannot install ytt

### ISSUE THREAD

**Issue by dteoh** [carvel-dev/setup-action#282]
I am getting the following error:

```
Run carvel-dev/setup-action@v1
Installing ytt:latest
Downloading ytt v0.45.1 from https://github.com/carvel-dev/ytt/releases/download/v0.45.1/ytt-linux-amd64
Error: Unable to verify checksum for ytt-linux-amd64. Expected to find "01606d885cdbce02340faadc29a83b5415280bc610e7cff3f639385d8f504aea  ./ytt-linux-amd64" in release notes.
```

It seems like the "Files Checksum" section in the ytt repo has an inconsistent format across the releases?

https://github.com/carvel-dev/ytt/releases

**Comment by sethiyash** [comment]
Hi @dteoh 
This is resolved now. Can you please try now?

**Comment by dteoh** [comment]
Thank you for the quick resolution, it is working again 🙇
