### ISSUE TITLE
Fails to verify checksum

### ISSUE THREAD

**Issue by eserte** [carvel-dev/setup-action#313]
Starting from yesterday the action fails with
```
Error: Unable to verify checksum for vendir-linux-amd64. Expected to find "59eba74240e96d96fae62c2cd2fdd2606dde9217fb1cd4c04a5a074a9afcb59e  ./vendir-linux-amd64" in release notes.
```
(or complaining on another checksum)

I think the problem is that the format of the release text changed slightly: instead of two spaces between checksum and file there's only one space, see here: https://github.com/carvel-dev/vendir/releases
Probably the action could be made more robust by using a regexp here which accepts any amount of whitespace.

**Comment by jbrunton** [comment]
@eserte: Thanks for raising. I think the release notes were fixed? It looks like there are two spaces now, and it worked for me when I ran a CI build just now. Lmk if you're still having issues and I'll investigate further.

This isn't the first time this has happened, and if it happens again I'll definitely consider adding regex, but the Carvel tools are supposed to standardise their release notes (see https://github.com/carvel-dev/setup-action/issues/65). The intended format is supposed to match the output you get from checksum tools, so this standard is helpful for anyone else who use these for verification.

**Comment by eserte** [comment]
Hi @jbrunton: I cannot check it in my workflow anymore, as the problem was "workarounded" by using the `only: kapp` option, and kapp release notes were not affected by the problem. I see the two spaces as well, so probably it's indeed fixed.
