### ISSUE TITLE
Checksum verification fails with v0.50.0 of ytt

### ISSUE THREAD

**Issue by adamconnelly** [carvel-dev/setup-action#321]
It looks like there's a similar issue to this previously reported problem: https://github.com/carvel-dev/setup-action/issues/313

This time it looks like the problem may be slightly different. The previous release notes for ytt included `./` before the filename, but the current version doesn't.

Here's the previous release notes:

![image](https://github.com/user-attachments/assets/f140d31b-0751-4ea0-9023-7de47c32dfc0)

Here's the current ones:

![image](https://github.com/user-attachments/assets/df7afcfa-9146-44d8-b3a6-00b5370d1971)

Apologies if it would make more sense to report this in the ytt repo - I'm just not quite sure what place makes most sense.

**Comment by Yserz** [comment]
We have the same problem and workaround it by pinning it to the previous version:
```
- uses: carvel-dev/setup-action@v2
  with:
    only: ytt
    ytt: v0.49.1
```

**Comment by adamconnelly** [comment]
I'm closing this issue - in the meantime it looks like the release notes have been fixed and the action is now working again with the latest ytt version. I've managed to successfully unpin the ytt version.
